databaseType = "MySql"
id = "6abdc028-d7f3-42c9-9f92-ec703f2c9c39"
name = "first_project"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.tw-media-prod]
url = "jdbc:mysql://localhost:3306"
schemas = [ "tw-media-prod" ]
displayName = "tw-media-prod"

[environments.tw-media-dev]
url = "jdbc:mysql://localhost:3306"
schemas = [ "tw-media-dev" ]
displayName = "tw-media-dev"
