CREATE TABLE `act_member_role` (
  `member_role_id` int NOT NULL,
  `member_role_name` varchar(32) NOT NULL,
  `member_role_type` varchar(16) NOT NULL,
  `member_role_desc` varchar(100) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `act_member` (
  `member_no` int NOT NULL AUTO_INCREMENT,
  `member_id` varchar(16) NOT NULL,
  `member_email` varchar(50) NOT NULL,
  `member_name` varchar(20) NOT NULL,
  `member_icon` varchar(1024) NOT NULL,
  `member_role_id` int NOT NULL,
  `password` varchar(128) NOT NULL,
  `lastest_selected_brand_id` varchar(32) NOT NULL,
  `age_checked` tinyint(1) NOT NULL DEFAULT '0',
  `terms_service_agreed` tinyint(1) NOT NULL DEFAULT '0',
  `terms_privacy_agreed` tinyint(1) NOT NULL DEFAULT '0',
  `marketing_mailing_agreed` tinyint(1) NOT NULL DEFAULT '0',
  `marketing_mailing_agreed_at` datetime DEFAULT NULL,
  `join_way` varchar(16) NOT NULL,
  `inviter_id` varchar(32) DEFAULT NULL,
  `status` int NOT NULL,
  `last_login_at` datetime DEFAULT NULL,
  `last_login_ip` varchar(50) DEFAULT NULL,
  `last_login_agent` text,
  `last_failed_login_at` datetime DEFAULT NULL,
  `last_failed_login_ip` varchar(50) DEFAULT NULL,
  `last_failed_login_agent` text,
  `failed_login_count` int NOT NULL DEFAULT '0',
  `password_changed_at` datetime DEFAULT NULL,
  `password_expires_at` datetime NOT NULL,
  `twofactor_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `twofactor_provider` varchar(32) DEFAULT NULL,
  `twofactor_secret` varchar(128) DEFAULT NULL,
  `twofactor_recovery_code` varchar(128) DEFAULT NULL,
  `is_locked` tinyint(1) NOT NULL DEFAULT '0',
  `locked_at` datetime DEFAULT NULL,
  `unlockable_expires_at` datetime DEFAULT NULL,
  `joined_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_no`),
  UNIQUE KEY `uix_member_id` (`member_id`),
  UNIQUE KEY `uix_member_email` (`member_email`),
  KEY `member_role_id` (`member_role_id`),
  CONSTRAINT `act_member_ibfk_1` FOREIGN KEY (`member_role_id`) REFERENCES `act_member_role` (`member_role_id`)
) ENGINE=InnoDB AUTO_INCREMENT=81 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `act_member_authentication` (
  `member_authentication_id` bigint NOT NULL AUTO_INCREMENT,
  `member_email` varchar(50) NOT NULL,
  `authentication_type` varchar(16) NOT NULL,
  `authentication_url` text,
  `authentication_code` varchar(512) DEFAULT NULL,
  `failed_attempts` int NOT NULL DEFAULT '0',
  `is_used` tinyint(1) NOT NULL DEFAULT '0',
  `expires_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_authentication_id`),
  KEY `ix_member_email_created_at` (`member_email`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=244 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;